#!/usr/bin/env python3
"""Generate fish completions for otter from internal/cli/show-file/*.help.

Run standalone (python3 tools/gencompletions/gen_fish.py) to regenerate just
completions/otter.fish, or via `make completions` to regenerate all three
shells. Uses the shared model/tables in model.py -- do not duplicate the
FLAG_TYPES/SPECIAL_VALUES/POSITIONAL_DYNAMIC tables here.
"""
import os
import sys

from model import (
    OUT_DIR,
    POSITIONAL_DYNAMIC,
    build_tree,
    walk,
)

# ---------------------------------------------------------------------------
# Fish renderer
# ---------------------------------------------------------------------------

def _fish_escape(desc):
    return desc.replace("'", "\\'")


def _fish_tokens(node):
    return [node.name] + ([node.alias] if node.alias else [])


def render_fish(root):
    all_nodes = list(walk(root))[1:]

    lines = []
    lines.append("# fish completion for otter")
    lines.append("# Drop in ~/.config/fish/completions/otter.fish")
    lines.append("#")
    lines.append("# Auto-generated by tools/gencompletions/gen_fish.py from")
    lines.append("# internal/cli/show-file/*.help -- do not edit by hand.")
    lines.append("# Run `make completions` to regenerate.")
    lines.append("")
    lines.append("complete -c otter -f")
    lines.append("")
    lines.append("function __otter_containers")
    lines.append('    otter list --json 2>/dev/null | string match -r \'"name": *"[^"]*"\' | string replace -r \'.*"name": *"([^"]*)".*\' \'$1\'')
    lines.append("end")
    lines.append("")
    lines.append("function __otter_registry_images")
    lines.append("    otter registry 2>/dev/null | tail -n +2 | awk '{print $1}'")
    lines.append("end")
    lines.append("")
    lines.append("function __otter_no_subcommand")
    lines.append("    not __fish_seen_subcommand_from \\")
    for node in [n for n in all_nodes if len(n.path) == 1]:
        toks = " ".join(_fish_tokens(node))
        lines.append(f"        {toks} \\")
    lines[-1] = lines[-1].rstrip(" \\")
    lines.append("end")
    lines.append("")
    lines.append("function __otter_using_subcommand")
    lines.append("    __fish_seen_subcommand_from $argv")
    lines.append("end")
    lines.append("")

    lines.append("# ── Global flags " + "─" * 62)
    for f in root.flags:
        short = f"-s {f.short.lstrip('-')} " if f.short else ""
        lines.append(f"complete -c otter -n __otter_no_subcommand -l {f.long.lstrip('-')} {short}-d '{_fish_escape(f.desc)}'")
    lines.append("")

    lines.append("# ── Top-level subcommands " + "─" * 54)
    for node in [n for n in all_nodes if len(n.path) == 1]:
        alias_note = f" (alias: {node.alias})" if node.alias else ""
        lines.append(
            f"complete -c otter -n __otter_no_subcommand -a {node.name} "
            f"-d '{_fish_escape(node.description)}{alias_note}'"
        )
    lines.append("")

    def ancestor_guard(node):
        """__otter_using_subcommand clauses for every ancestor level, ANDed together."""
        clauses = []
        cur = root
        for part in node.path[:-1]:
            cur = cur.children[part]
            toks = " ".join(_fish_tokens(cur))
            clauses.append(f"__otter_using_subcommand {toks}")
        return clauses

    def emit_node(node):
        toks = " ".join(_fish_tokens(node))
        own_clauses = ancestor_guard(node) + [f"__otter_using_subcommand {toks}"]

        if node.children:
            not_children = " ".join(t for c in node.children.values() for t in _fish_tokens(c))
            guard = "; and ".join(own_clauses) + f"; and not __fish_seen_subcommand_from {not_children}"
        else:
            guard = "; and ".join(own_clauses)

        lines.append(f"# ── {node.full_key} " + "─" * max(1, 70 - len(node.full_key)))
        for f in node.flags:
            short = f"-s {f.short.lstrip('-')} " if f.short else ""
            lines.append(f"complete -c otter -n '{guard}' -l {f.long.lstrip('-')} {short}-d '{_fish_escape(f.desc)}'")

        dynamic_target = POSITIONAL_DYNAMIC.get(node.path)
        if dynamic_target and not node.children:
            helper = "__otter_containers" if dynamic_target == "containers" else "__otter_registry_images"
            lines.append(f"complete -c otter -n '{guard}' -a '({helper})'")

        if node.children:
            for child in node.children.values():
                alias_note = f" (alias: {child.alias})" if child.alias else ""
                lines.append(
                    f"complete -c otter -n '{guard}' -a {child.name} "
                    f"-d '{_fish_escape(child.description)}{alias_note}'"
                )
        lines.append("")

        for child in node.children.values():
            emit_node(child)

    for node in [n for n in all_nodes if len(n.path) == 1]:
        emit_node(node)

    return "\n".join(lines)


if __name__ == "__main__":
    tree = build_tree()
    fish_out = render_fish(tree)
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "otter.fish"), "w") as f:
        f.write(fish_out)
    print("wrote fish completions to", OUT_DIR, file=sys.stderr)