#!/usr/bin/env python3
"""Generate zsh completions for otter from internal/cli/show-file/*.help.

Run standalone (python3 tools/gencompletions/gen_zsh.py) to regenerate just
completions/otter.zsh, or via `make completions` to regenerate all three
shells. Uses the shared model/tables in model.py -- do not duplicate the
FLAG_TYPES/SPECIAL_VALUES/POSITIONAL_DYNAMIC tables here.
"""
import os
import sys

from model import (
    OUT_DIR,
    POSITIONAL_DYNAMIC,
    build_tree,
    flag_kind,
    special_for,
    walk,
)

# ---------------------------------------------------------------------------
# Zsh renderer
# ---------------------------------------------------------------------------

def _zsh_escape(desc):
    return desc.replace("'", "'\\''")


def _zsh_flag_spec(node, f):
    kind = flag_kind(node.path, f.long)
    desc = _zsh_escape(f.desc)
    if f.short:
        excl = f"'({f.long} {f.short})'{{{f.long},{f.short}}}"
    else:
        excl = f"'{f.long}'"

    if kind == "bool":
        return f"{excl}'[{desc}]'"

    sp = special_for(node.path, f.long)
    if sp is None:
        action = ""
    elif sp[0] == "enum":
        action = "(" + " ".join(sp[1]) + ")"
    elif sp[1] == "containers":
        action = "_otter_container_names"
    else:
        action = "_otter_registry_image_names"
    return f"{excl}'[{desc}]:value:{action}'"


def render_zsh(root):
    all_nodes = list(walk(root))

    lines = []
    lines.append("#compdef otter")
    lines.append("# zsh completion for otter")
    lines.append("# Drop in $fpath, e.g. /usr/local/share/zsh/site-functions/_otter")
    lines.append("# or ~/.local/share/zsh/site-functions/_otter (add dir to fpath first)")
    lines.append("#")
    lines.append("# Auto-generated by tools/gencompletions/gen_zsh.py from")
    lines.append("# internal/cli/show-file/*.help -- do not edit by hand.")
    lines.append("# Run `make completions` to regenerate.")
    lines.append("")
    lines.append("_otter_container_names() {")
    lines.append("    local -a containers")
    lines.append('    containers=( ${(f)"$(otter list --json 2>/dev/null | grep \'"name"\' | sed \'s/.*"name": *"\\([^"]*\\)".*/\\1/\')"} )')
    lines.append("    compadd -a containers")
    lines.append("}")
    lines.append("")
    lines.append("_otter_registry_image_names() {")
    lines.append("    local -a images")
    lines.append("    images=( ${(f)\"$(otter registry 2>/dev/null | awk 'NR>1 {print $1}')\"} )")
    lines.append("    compadd -a images")
    lines.append("}")
    lines.append("")

    def emit_node(node):
        fn_suffix = "_".join(node.path).replace("-", "_")
        fn_name = f"_otter_{fn_suffix}" if node.path else "_otter"

        specs = [_zsh_flag_spec(node, f) for f in node.flags]
        positional = POSITIONAL_DYNAMIC.get(node.path)

        if node.children:
            lines.append(f"{fn_name}() {{")
            lines.append("    local state")
            lines.append("    _arguments -C \\")
            for spec in specs:
                lines.append(f"        {spec} \\")
            lines.append(f"        '1: :{fn_name}_subcommands' \\")
            lines.append("        '*:: :->sub' \\")
            lines.append("        && return")
            lines.append("")
            lines.append('    case "${state}" in')
            lines.append("        sub)")
            lines.append('            case "${words[1]}" in')
            for child in node.children.values():
                tokens = child.name + (("|" + child.alias) if child.alias else "")
                child_fn = f"_otter_{'_'.join(child.path).replace('-', '_')}"
                lines.append(f"                {tokens}) {child_fn} ;;")
            lines.append("            esac")
            lines.append("            ;;")
            lines.append("    esac")
            lines.append("}")
            lines.append("")

            lines.append(f"{fn_name}_subcommands() {{")
            lines.append("    local -a subcmds")
            lines.append("    subcmds=(")
            for child in node.children.values():
                desc = _zsh_escape(child.description)
                alias_note = f" (alias: {child.alias})" if child.alias else ""
                lines.append(f"        '{child.name}:{desc}{alias_note}'")
            lines.append("    )")
            label = node.name if node.path else "command"
            lines.append(f"    _describe '{label} subcommand' subcmds")
            lines.append("}")
            lines.append("")
        else:
            lines.append(f"{fn_name}() {{")
            lines.append("    _arguments \\")
            all_specs = list(specs)
            if positional == "containers":
                all_specs.insert(0, "'*:container:_otter_container_names'")
            elif positional == "registry_images":
                all_specs.insert(0, "'*:image:_otter_registry_image_names'")
            for idx, spec in enumerate(all_specs):
                sep = " \\" if idx < len(all_specs) - 1 else ""
                lines.append(f"        {spec}{sep}")
            lines.append("}")
            lines.append("")

        for child in node.children.values():
            emit_node(child)

    emit_node(root)

    lines.append("compdef _otter otter")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    tree = build_tree()
    zsh_out = render_zsh(tree)
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "otter.zsh"), "w") as f:
        f.write(zsh_out)
    print("wrote zsh completions to", OUT_DIR, file=sys.stderr)