#!/usr/bin/env python3
"""Generate bash completions for otter from internal/cli/show-file/*.help.

Run standalone (python3 tools/gencompletions/gen_bash.py) to regenerate just
completions/otter.bash, or via `make completions` to regenerate all three
shells. Uses the shared model/tables in model.py -- do not duplicate the
FLAG_TYPES/SPECIAL_VALUES/POSITIONAL_DYNAMIC tables here.
"""
import os
import sys

from model import (
    OUT_DIR,
    POSITIONAL_DYNAMIC,
    build_tree,
    flag_kind,
    special_for,
    walk,
)

# ---------------------------------------------------------------------------
# Bash renderer
# ---------------------------------------------------------------------------

def _bash_value_candidates(kind_info):
    """kind_info is the ('enum', (...)) | ('dynamic', name) tuple from SPECIAL_VALUES."""
    sub_kind, payload = kind_info
    if sub_kind == "enum":
        words = " ".join(payload)
        return f'mapfile -t COMPREPLY < <(compgen -W "{words}" -- "${{cur}}")\n                    return\n                    ;;'
    # dynamic
    helper = "_otter_containers" if payload == "containers" else "_otter_registry_images"
    varname = "containers" if payload == "containers" else "images"
    return (
        f"local {varname}\n"
        f"                    {varname}=$({helper})\n"
        f'                    mapfile -t COMPREPLY < <(compgen -W "${{{varname}}}" -- "${{cur}}")\n'
        f"                    return\n"
        f"                    ;;"
    )


def render_bash(root):
    all_nodes = list(walk(root))[1:]  # skip root itself, it has no "path"

    # tree lookup table: "<parent path str>|<token>" -> "<resolved path str>"
    tree_entries = []
    for node in all_nodes:
        parent_path = " ".join(node.path[:-1])
        for token in [node.name] + ([node.alias] if node.alias else []):
            tree_entries.append(f'    ["{parent_path}|{token}"]="{node.full_key}"')

    lines = []
    lines.append("# bash completion for otter")
    lines.append("# Source this file or drop it in /etc/bash_completion.d/otter")
    lines.append("# or ~/.local/share/bash-completion/completions/otter")
    lines.append("#")
    lines.append("# Auto-generated by tools/gencompletions/gen_bash.py from")
    lines.append("# internal/cli/show-file/*.help -- do not edit by hand.")
    lines.append("# Run `make completions` to regenerate.")
    lines.append("")
    lines.append("_otter_containers() {")
    lines.append('    otter list --json 2>/dev/null | grep \'"name"\' | sed \'s/.*"name": *"\\([^"]*\\)".*/\\1/\'')
    lines.append("}")
    lines.append("")
    lines.append("_otter_registry_images() {")
    lines.append("    otter registry 2>/dev/null | awk 'NR>1 {print $1}'")
    lines.append("}")
    lines.append("")
    lines.append("_otter() {")
    lines.append("    local cur prev words cword")
    lines.append('    _init_completion -n "=:" || return')
    lines.append("")
    lines.append("    local -A _otter_tree=(")
    lines.extend(tree_entries)
    lines.append("    )")
    lines.append("")
    lines.append('    local path=""')
    lines.append("    local i")
    lines.append("    # shellcheck disable=SC2249")
    lines.append("    for (( i=1; i < cword; i++ )); do")
    lines.append('        local key="${path}|${words[i]}"')
    lines.append('        if [[ -n "${_otter_tree[$key]+x}" ]]; then')
    lines.append('            path="${_otter_tree[$key]}"')
    lines.append("        else")
    lines.append("            break")
    lines.append("        fi")
    lines.append("    done")
    lines.append("")
    lines.append('    case "${path}" in')
    lines.append('        "")')
    root_flag_names = " ".join(f.long for f in root.flags)
    top_commands = " ".join(n.name for n in all_nodes if len(n.path) == 1)
    lines.append(f'            mapfile -t COMPREPLY < <(compgen -W "{top_commands} {root_flag_names}" -- "${{cur}}")')
    lines.append("            ;;")

    for node in all_nodes:
        lines.append(f'        "{node.full_key}")')
        # prev-based special value completions
        special_cases = []
        plain_value_flags = []
        for f in node.flags:
            kind = flag_kind(node.path, f.long)
            if kind != "value":
                continue
            sp = special_for(node.path, f.long)
            if sp:
                special_cases.append(f"                {f.long})\n                    {_bash_value_candidates(sp)}")
            else:
                plain_value_flags.append(f.long)
        if plain_value_flags:
            joined = "|".join(plain_value_flags)
            special_cases.append(f"                {joined}) return ;;")
        if special_cases:
            lines.append("            # shellcheck disable=SC2249")
            lines.append('            case "${prev}" in')
            lines.extend(special_cases)
            lines.append("            esac")

        dynamic_target = POSITIONAL_DYNAMIC.get(node.path)
        if dynamic_target:
            helper = "_otter_containers" if dynamic_target == "containers" else "_otter_registry_images"
            varname = "containers" if dynamic_target == "containers" else "images"
            lines.append('            local has_positional=0')
            lines.append("            # shellcheck disable=SC2249")
            lines.append(f"            for (( i={len(node.path) + 1}; i < cword; i++ )); do")
            lines.append('                [[ "${words[i]}" != -* ]] && has_positional=1 && break')
            lines.append("            done")
            lines.append('            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then')
            lines.append(f"                local {varname}")
            lines.append(f"                {varname}=$({helper})")
            lines.append(f'                mapfile -t COMPREPLY < <(compgen -W "${{{varname}}}" -- "${{cur}}")')
            lines.append("                return")
            lines.append("            fi")

        flag_names = " ".join(f.long for f in node.flags)
        child_names = " ".join(c.name for c in node.children.values())
        all_words = " ".join(w for w in [child_names, flag_names] if w)
        lines.append(f'            mapfile -t COMPREPLY < <(compgen -W "{all_words}" -- "${{cur}}")')
        lines.append("            ;;")

    lines.append("    esac")
    lines.append("}")
    lines.append("")
    lines.append("complete -F _otter otter")
    lines.append("")
    return "\n".join(lines)

if __name__ == "__main__":
    tree = build_tree()
    bash_out = render_bash(tree)
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "otter.bash"), "w") as f:
        f.write(bash_out)
    print("wrote bash completions to", OUT_DIR, file=sys.stderr)