# bash completion for otter
# Source this file or drop it in /etc/bash_completion.d/otter
# or ~/.local/share/bash-completion/completions/otter
#
# Auto-generated by tools/gencompletions/gen_bash.py from
# internal/cli/show-file/*.help -- do not edit by hand.
# Run `make completions` to regenerate.

_otter_containers() {
    otter list --json 2>/dev/null | grep '"name"' | sed 's/.*"name": *"\([^"]*\)".*/\1/'
}

_otter_registry_images() {
    otter registry 2>/dev/null | awk 'NR>1 {print $1}'
}

_otter() {
    local cur prev words cword
    _init_completion -n "=:" || return

    local -A _otter_tree=(
    ["|assemble"]="assemble"
    ["|dmf"]="assemble"
    ["assemble|create"]="assemble create"
    ["assemble|mk"]="assemble create"
    ["assemble|remove"]="assemble remove"
    ["assemble|rm"]="assemble remove"
    ["|create"]="create"
    ["|mk"]="create"
    ["|enter"]="enter"
    ["|sh"]="enter"
    ["|generate-entry"]="generate-entry"
    ["|pin"]="generate-entry"
    ["|inspect"]="inspect"
    ["|info"]="inspect"
    ["|journal"]="journal"
    ["|logs"]="journal"
    ["|list"]="list"
    ["|ls"]="list"
    ["|lock"]="lock"
    ["|lk"]="lock"
    ["|pause"]="pause"
    ["|zz"]="pause"
    ["|registry"]="registry"
    ["|reg"]="registry"
    ["registry|list"]="registry list"
    ["registry|ls"]="registry list"
    ["registry|pull"]="registry pull"
    ["registry|pl"]="registry pull"
    ["registry|remove"]="registry remove"
    ["registry|rm"]="registry remove"
    ["|remove"]="remove"
    ["|rm"]="remove"
    ["|restart"]="restart"
    ["|rbt"]="restart"
    ["|start"]="start"
    ["|up"]="start"
    ["|stop"]="stop"
    ["|dn"]="stop"
    ["|unlock"]="unlock"
    ["|ulk"]="unlock"
    ["|upgrade"]="upgrade"
    ["|syu"]="upgrade"
    )

    local path=""
    local i
    # shellcheck disable=SC2249
    for (( i=1; i < cword; i++ )); do
        local key="${path}|${words[i]}"
        if [[ -n "${_otter_tree[$key]+x}" ]]; then
            path="${_otter_tree[$key]}"
        else
            break
        fi
    done

    case "${path}" in
        "")
            mapfile -t COMPREPLY < <(compgen -W "assemble create enter generate-entry inspect journal list lock pause registry remove restart start stop unlock upgrade --help --version" -- "${cur}")
            ;;
        "assemble")
            # shellcheck disable=SC2249
            case "${prev}" in
                --file) return ;;
            esac
            mapfile -t COMPREPLY < <(compgen -W "create remove --file --replace --help" -- "${cur}")
            ;;
        "assemble create")
            # shellcheck disable=SC2249
            case "${prev}" in
                --file) return ;;
            esac
            mapfile -t COMPREPLY < <(compgen -W "--file --replace --help" -- "${cur}")
            ;;
        "assemble remove")
            # shellcheck disable=SC2249
            case "${prev}" in
                --file) return ;;
            esac
            mapfile -t COMPREPLY < <(compgen -W "--file --help" -- "${cur}")
            ;;
        "create")
            # shellcheck disable=SC2249
            case "${prev}" in
                --clone)
                    local containers
                    containers=$(_otter_containers)
                    mapfile -t COMPREPLY < <(compgen -W "${containers}" -- "${cur}")
                    return
                    ;;
                --image)
                    local images
                    images=$(_otter_registry_images)
                    mapfile -t COMPREPLY < <(compgen -W "${images}" -- "${cur}")
                    return
                    ;;
                --shell)
                    mapfile -t COMPREPLY < <(compgen -W "bash zsh fish" -- "${cur}")
                    return
                    ;;
                --platform)
                    mapfile -t COMPREPLY < <(compgen -W "linux/amd64 linux/arm64 linux/arm/v7 linux/386" -- "${cur}")
                    return
                    ;;
                --home|--memory|--volume|--hostname|--init-hooks|--cpu-threads|--pre-init-hooks|--additional-flags|--additional-packages) return ;;
            esac
            mapfile -t COMPREPLY < <(compgen -W "--home --init --root --clone --image --shell --memory --nvidia --volume --hostname --no-entry --platform --init-hooks --cpu-threads --unshare-ipc --unshare-all --always-pull --unshare-netns --pre-init-hooks --unshare-groups --unshare-devsys --unshare-process --no-userns-limit --additional-flags --additional-packages --help --disable-root-password-i-fully-understand-the-risks-and-accept-the-responsibilities" -- "${cur}")
            ;;
        "enter")
            # shellcheck disable=SC2249
            case "${prev}" in
                --add-env|--additional-flags) return ;;
            esac
            local has_positional=0
            # shellcheck disable=SC2249
            for (( i=2; i < cword; i++ )); do
                [[ "${words[i]}" != -* ]] && has_positional=1 && break
            done
            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then
                local containers
                containers=$(_otter_containers)
                mapfile -t COMPREPLY < <(compgen -W "${containers}" -- "${cur}")
                return
            fi
            mapfile -t COMPREPLY < <(compgen -W "--root --no-tty --add-env --empty-env --clean-path --no-workdir --auto-start --additional-flags --help" -- "${cur}")
            ;;
        "generate-entry")
            # shellcheck disable=SC2249
            case "${prev}" in
                --icon) return ;;
            esac
            local has_positional=0
            # shellcheck disable=SC2249
            for (( i=2; i < cword; i++ )); do
                [[ "${words[i]}" != -* ]] && has_positional=1 && break
            done
            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then
                local containers
                containers=$(_otter_containers)
                mapfile -t COMPREPLY < <(compgen -W "${containers}" -- "${cur}")
                return
            fi
            mapfile -t COMPREPLY < <(compgen -W "--all --root --icon --delete --help" -- "${cur}")
            ;;
        "inspect")
            local has_positional=0
            # shellcheck disable=SC2249
            for (( i=2; i < cword; i++ )); do
                [[ "${words[i]}" != -* ]] && has_positional=1 && break
            done
            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then
                local containers
                containers=$(_otter_containers)
                mapfile -t COMPREPLY < <(compgen -W "${containers}" -- "${cur}")
                return
            fi
            mapfile -t COMPREPLY < <(compgen -W "--root --json --help" -- "${cur}")
            ;;
        "journal")
            # shellcheck disable=SC2249
            case "${prev}" in
                --tail|--since|--until) return ;;
            esac
            local has_positional=0
            # shellcheck disable=SC2249
            for (( i=2; i < cword; i++ )); do
                [[ "${words[i]}" != -* ]] && has_positional=1 && break
            done
            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then
                local containers
                containers=$(_otter_containers)
                mapfile -t COMPREPLY < <(compgen -W "${containers}" -- "${cur}")
                return
            fi
            mapfile -t COMPREPLY < <(compgen -W "--tail --since --until --follow --timestamps --help" -- "${cur}")
            ;;
        "list")
            mapfile -t COMPREPLY < <(compgen -W "--root --json --help" -- "${cur}")
            ;;
        "lock")
            local has_positional=0
            # shellcheck disable=SC2249
            for (( i=2; i < cword; i++ )); do
                [[ "${words[i]}" != -* ]] && has_positional=1 && break
            done
            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then
                local containers
                containers=$(_otter_containers)
                mapfile -t COMPREPLY < <(compgen -W "${containers}" -- "${cur}")
                return
            fi
            mapfile -t COMPREPLY < <(compgen -W "--all --root --help" -- "${cur}")
            ;;
        "pause")
            local has_positional=0
            # shellcheck disable=SC2249
            for (( i=2; i < cword; i++ )); do
                [[ "${words[i]}" != -* ]] && has_positional=1 && break
            done
            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then
                local containers
                containers=$(_otter_containers)
                mapfile -t COMPREPLY < <(compgen -W "${containers}" -- "${cur}")
                return
            fi
            mapfile -t COMPREPLY < <(compgen -W "--all --root --help" -- "${cur}")
            ;;
        "registry")
            mapfile -t COMPREPLY < <(compgen -W "list pull remove --help" -- "${cur}")
            ;;
        "registry list")
            mapfile -t COMPREPLY < <(compgen -W "--all --help" -- "${cur}")
            ;;
        "registry pull")
            local has_positional=0
            # shellcheck disable=SC2249
            for (( i=3; i < cword; i++ )); do
                [[ "${words[i]}" != -* ]] && has_positional=1 && break
            done
            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then
                local images
                images=$(_otter_registry_images)
                mapfile -t COMPREPLY < <(compgen -W "${images}" -- "${cur}")
                return
            fi
            mapfile -t COMPREPLY < <(compgen -W "--all --force --help" -- "${cur}")
            ;;
        "registry remove")
            local has_positional=0
            # shellcheck disable=SC2249
            for (( i=3; i < cword; i++ )); do
                [[ "${words[i]}" != -* ]] && has_positional=1 && break
            done
            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then
                local images
                images=$(_otter_registry_images)
                mapfile -t COMPREPLY < <(compgen -W "${images}" -- "${cur}")
                return
            fi
            mapfile -t COMPREPLY < <(compgen -W "--all --force --help" -- "${cur}")
            ;;
        "remove")
            local has_positional=0
            # shellcheck disable=SC2249
            for (( i=2; i < cword; i++ )); do
                [[ "${words[i]}" != -* ]] && has_positional=1 && break
            done
            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then
                local containers
                containers=$(_otter_containers)
                mapfile -t COMPREPLY < <(compgen -W "${containers}" -- "${cur}")
                return
            fi
            mapfile -t COMPREPLY < <(compgen -W "--all --root --force --rm-home --bypass-lock --help" -- "${cur}")
            ;;
        "restart")
            local has_positional=0
            # shellcheck disable=SC2249
            for (( i=2; i < cword; i++ )); do
                [[ "${words[i]}" != -* ]] && has_positional=1 && break
            done
            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then
                local containers
                containers=$(_otter_containers)
                mapfile -t COMPREPLY < <(compgen -W "${containers}" -- "${cur}")
                return
            fi
            mapfile -t COMPREPLY < <(compgen -W "--all --root --force --help" -- "${cur}")
            ;;
        "start")
            local has_positional=0
            # shellcheck disable=SC2249
            for (( i=2; i < cword; i++ )); do
                [[ "${words[i]}" != -* ]] && has_positional=1 && break
            done
            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then
                local containers
                containers=$(_otter_containers)
                mapfile -t COMPREPLY < <(compgen -W "${containers}" -- "${cur}")
                return
            fi
            mapfile -t COMPREPLY < <(compgen -W "--all --root --help" -- "${cur}")
            ;;
        "stop")
            local has_positional=0
            # shellcheck disable=SC2249
            for (( i=2; i < cword; i++ )); do
                [[ "${words[i]}" != -* ]] && has_positional=1 && break
            done
            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then
                local containers
                containers=$(_otter_containers)
                mapfile -t COMPREPLY < <(compgen -W "${containers}" -- "${cur}")
                return
            fi
            mapfile -t COMPREPLY < <(compgen -W "--all --root --force --help" -- "${cur}")
            ;;
        "unlock")
            local has_positional=0
            # shellcheck disable=SC2249
            for (( i=2; i < cword; i++ )); do
                [[ "${words[i]}" != -* ]] && has_positional=1 && break
            done
            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then
                local containers
                containers=$(_otter_containers)
                mapfile -t COMPREPLY < <(compgen -W "${containers}" -- "${cur}")
                return
            fi
            mapfile -t COMPREPLY < <(compgen -W "--all --root --help" -- "${cur}")
            ;;
        "upgrade")
            local has_positional=0
            # shellcheck disable=SC2249
            for (( i=2; i < cword; i++ )); do
                [[ "${words[i]}" != -* ]] && has_positional=1 && break
            done
            if [[ "${cur}" != -* && "${has_positional}" -eq 0 ]]; then
                local containers
                containers=$(_otter_containers)
                mapfile -t COMPREPLY < <(compgen -W "${containers}" -- "${cur}")
                return
            fi
            mapfile -t COMPREPLY < <(compgen -W "--all --root --running --help" -- "${cur}")
            ;;
    esac
}

complete -F _otter otter
