#compdef otter
# zsh completion for otter
# Drop in $fpath, e.g. /usr/local/share/zsh/site-functions/_otter
# or ~/.local/share/zsh/site-functions/_otter (add dir to fpath first)
#
# Auto-generated by tools/gencompletions/generate_completions.py from
# internal/cli/show-file/*.help -- do not edit by hand.
# Run `make completions` to regenerate.

_otter_container_names() {
    local -a containers
    containers=( ${(f)"$(otter list --json 2>/dev/null | grep '"name"' | sed 's/.*"name": *"\([^"]*\)".*/\1/')"} )
    compadd -a containers
}

_otter_registry_image_names() {
    local -a images
    images=( ${(f)"$(otter registry 2>/dev/null | awk 'NR>1 {print $1}')"} )
    compadd -a images
}

_otter() {
    local state
    _arguments -C \
        '(--help -h)'{--help,-h}'[Show this help message]' \
        '(--version -v)'{--version,-v}'[Print version information]' \
        '1: :_otter_subcommands' \
        '*:: :->sub' \
        && return

    case "${state}" in
        sub)
            case "${words[1]}" in
                assemble|dmf) _otter_assemble ;;
                create|mk) _otter_create ;;
                enter|sh) _otter_enter ;;
                generate-entry|pin) _otter_generate_entry ;;
                inspect|info) _otter_inspect ;;
                journal|logs) _otter_journal ;;
                list|ls) _otter_list ;;
                lock|lk) _otter_lock ;;
                pause|zz) _otter_pause ;;
                registry|reg) _otter_registry ;;
                remove|rm) _otter_remove ;;
                restart|rbt) _otter_restart ;;
                start|up) _otter_start ;;
                stop|dn) _otter_stop ;;
                unlock|ulk) _otter_unlock ;;
                upgrade|syu) _otter_upgrade ;;
            esac
            ;;
    esac
}

_otter_subcommands() {
    local -a subcmds
    subcmds=(
        'assemble:Manage otter containers using manifest files (alias: dmf)'
        'create:Create native distro like container environments using otter (alias: mk)'
        'enter:Enter into a otter managed container environment (alias: sh)'
        'generate-entry:Generate desktop entry for containers (alias: pin)'
        'inspect:Show info of an otter managed container (alias: info)'
        'journal:Show logs of an otter managed container (alias: logs)'
        'list:List all otter managed containers (alias: ls)'
        'lock:Lock a container to prevent removal or upgrades (alias: lk)'
        'pause:Pause an otter managed running container (alias: zz)'
        'registry:Browse and manage otter images from the registry (alias: reg)'
        'remove:Remove otter managed container environments (alias: rm)'
        'restart:Restart an otter managed container environment (alias: rbt)'
        'start:Start an otter managed container environment (alias: up)'
        'stop:Stop an otter managed running container environment (alias: dn)'
        'unlock:Unlock a container to allow removal and upgrades (alias: ulk)'
        'upgrade:Upgrade packages inside otter managed containers (alias: syu)'
    )
    _describe 'command subcommand' subcmds
}

_otter_assemble() {
    local state
    _arguments -C \
        '(--file -f)'{--file,-f}'[Path or URL to the manifest/ini file]:value:' \
        '(--replace -R)'{--replace,-R}'[Replace containers with matching names]' \
        '(--help -h)'{--help,-h}'[Show this help message]' \
        '1: :_otter_assemble_subcommands' \
        '*:: :->sub' \
        && return

    case "${state}" in
        sub)
            case "${words[1]}" in
                create|mk) _otter_assemble_create ;;
                remove|rm) _otter_assemble_remove ;;
            esac
            ;;
    esac
}

_otter_assemble_subcommands() {
    local -a subcmds
    subcmds=(
        'create:Create or update otters defined in a manifest file (alias: mk)'
        'remove:Remove otters defined in a manifest file (alias: rm)'
    )
    _describe 'assemble subcommand' subcmds
}

_otter_assemble_create() {
    _arguments \
        '(--file -f)'{--file,-f}'[Path to the manifest file (required)]:value:' \
        '(--replace -R)'{--replace,-R}'[Delete and recreate boxes that already exist]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_assemble_remove() {
    _arguments \
        '(--file -f)'{--file,-f}'[Path to the manifest file (required)]:value:' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_create() {
    _arguments \
        '(--home -H)'{--home,-H}'[Custom HOME directory for the container]:value:' \
        '(--init -I)'{--init,-I}'[Use init system (e.g. systemd) inside the container]' \
        '(--root -r)'{--root,-r}'[Launch container manager with root privileges]' \
        '(--clone -C)'{--clone,-C}'[Name of container to use as base for new container]:value:_otter_container_names' \
        '(--image -i)'{--image,-i}'[Image to use for the container]:value:_otter_registry_image_names' \
        '(--shell -s)'{--shell,-s}'[Shell to use inside the container]:value:(bash zsh fish)' \
        '(--memory -m)'{--memory,-m}'[Memory limit for the container (e.g. 512m, 2g)]:value:' \
        '(--nvidia -N)'{--nvidia,-N}'[Integrate host'\''s Nvidia drivers into container]' \
        '(--volume -v)'{--volume,-v}'[Additional volumes to add to the container]:value:' \
        '(--hostname -n)'{--hostname,-n}'[Hostname for the container]:value:' \
        '(--no-entry -E)'{--no-entry,-E}'[Do not generate a container entry on host system]' \
        '(--platform -P)'{--platform,-P}'[Specify the target platform, e.g. linux/arm64]:value:(linux/amd64 linux/arm64 linux/arm/v7 linux/386)' \
        '(--init-hooks -ih)'{--init-hooks,-ih}'[Commands to run at end of container initialization]:value:' \
        '(--cpu-threads -t)'{--cpu-threads,-t}'[Number of CPU threads the container can use]:value:' \
        '(--unshare-ipc -ui)'{--unshare-ipc,-ui}'[Do not share IPC namespace with host]' \
        '(--unshare-all -ua)'{--unshare-all,-ua}'[Activate all unshare flags]' \
        '(--always-pull -p)'{--always-pull,-p}'[Pull image even if it exists locally]' \
        '(--unshare-netns -un)'{--unshare-netns,-un}'[Do not share net namespace with host]' \
        '(--pre-init-hooks -ph)'{--pre-init-hooks,-ph}'[Commands to run at start of container initialization]:value:' \
        '(--unshare-groups -ug)'{--unshare-groups,-ug}'[Do not forward user'\''s additional groups into container]' \
        '(--unshare-devsys -ud)'{--unshare-devsys,-ud}'[Do not share host devices and sysfs dirs]' \
        '(--unshare-process -up)'{--unshare-process,-up}'[Do not share process namespace with host]' \
        '(--no-userns-limit -ul)'{--no-userns-limit,-ul}'[Skip the size-capped userns range for podman]' \
        '(--additional-flags -a)'{--additional-flags,-a}'[Additional flags to pass to the container manager]:value:' \
        '(--additional-packages -ap)'{--additional-packages,-ap}'[Additional packages to install during container setup]:value:' \
        '(--help -h)'{--help,-h}'[Show this help message]' \
        '--disable-root-password-i-fully-understand-the-risks-and-accept-the-responsibilities''[]'
}

_otter_enter() {
    _arguments \
        '*:container:_otter_container_names' \
        '(--root -r)'{--root,-r}'[Launch container manager with root privileges]' \
        '(--no-tty -T)'{--no-tty,-T}'[Do not instantiate a tty]' \
        '(--add-env -e)'{--add-env,-e}'[Comma-separated list of host env vars to copy]:value:' \
        '(--empty-env -E)'{--empty-env,-E}'[Don'\''t auto copy host environment variables]' \
        '--clean-path''[Reset PATH inside container to FHS standard]' \
        '(--no-workdir -nw)'{--no-workdir,-nw}'[Always start from container'\''s home directory]' \
        '(--auto-start -S)'{--auto-start,-S}'[Start container if stopped, then enter]' \
        '(--additional-flags -a)'{--additional-flags,-a}'[Additional flags to pass to container manager]:value:' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_generate_entry() {
    _arguments \
        '*:container:_otter_container_names' \
        '(--all -a)'{--all,-a}'[Perform for all otters]' \
        '(--root -r)'{--root,-r}'[Perform on rootful otters]' \
        '(--icon -i)'{--icon,-i}'[Specify a custom icon path]:value:' \
        '(--delete -d)'{--delete,-d}'[Delete the entry]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_inspect() {
    _arguments \
        '*:container:_otter_container_names' \
        '(--root -r)'{--root,-r}'[Inspect a rootful container]' \
        '(--json -j)'{--json,-j}'[Show inspect as json struct]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_journal() {
    _arguments \
        '*:container:_otter_container_names' \
        '(--tail -n)'{--tail,-n}'[Show last N lines]:value:' \
        '(--since -s)'{--since,-s}'[Show logs since duration]:value:' \
        '(--until -u)'{--until,-u}'[Show logs until duration]:value:' \
        '(--follow -f)'{--follow,-f}'[Stream logs live]' \
        '(--timestamps -t)'{--timestamps,-t}'[Show timestamps on each line]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_list() {
    _arguments \
        '(--root -r)'{--root,-r}'[List rootful containers]' \
        '(--json -j)'{--json,-j}'[Show list as json struct]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_lock() {
    _arguments \
        '*:container:_otter_container_names' \
        '(--all -a)'{--all,-a}'[Lock all otter containers]' \
        '(--root -r)'{--root,-r}'[Lock a rootful container]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_pause() {
    _arguments \
        '*:container:_otter_container_names' \
        '(--all -a)'{--all,-a}'[Pause all running otters]' \
        '(--root -r)'{--root,-r}'[Pause rootful containers]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_registry() {
    local state
    _arguments -C \
        '(--help -h)'{--help,-h}'[Show this help message]' \
        '1: :_otter_registry_subcommands' \
        '*:: :->sub' \
        && return

    case "${state}" in
        sub)
            case "${words[1]}" in
                list|ls) _otter_registry_list ;;
                pull|pl) _otter_registry_pull ;;
                remove|rm) _otter_registry_remove ;;
            esac
            ;;
    esac
}

_otter_registry_subcommands() {
    local -a subcmds
    subcmds=(
        'list:List otter images available in the registry (alias: ls)'
        'pull:Pull otter images from the registry (alias: pl)'
        'remove:Remove otter images from the local registry cache (alias: rm)'
    )
    _describe 'registry subcommand' subcmds
}

_otter_registry_list() {
    _arguments \
        '(--all -a)'{--all,-a}'[Include disabled images in the table]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_registry_pull() {
    _arguments \
        '*:image:_otter_registry_image_names' \
        '(--all -a)'{--all,-a}'[Pull all enabled images not yet present]' \
        '(--force -f)'{--force,-f}'[Pull even if already present and current]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_registry_remove() {
    _arguments \
        '*:image:_otter_registry_image_names' \
        '(--all -a)'{--all,-a}'[Remove all locally present otter images]' \
        '(--force -f)'{--force,-f}'[Remove even if image is in use]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_remove() {
    _arguments \
        '*:container:_otter_container_names' \
        '(--all -a)'{--all,-a}'[Delete all otters]' \
        '(--root -r)'{--root,-r}'[Launch container with root privileges]' \
        '(--force -f)'{--force,-f}'[Force deletion of problematic containers]' \
        '(--rm-home -H)'{--rm-home,-H}'[Remove container'\''s custom home directory]' \
        '(--bypass-lock -B)'{--bypass-lock,-B}'[Remove container even if it is locked]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_restart() {
    _arguments \
        '*:container:_otter_container_names' \
        '(--all -a)'{--all,-a}'[Restart all otter containers]' \
        '(--root -r)'{--root,-r}'[Restart rootful containers]' \
        '(--force -f)'{--force,-f}'[Force restart containers]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_start() {
    _arguments \
        '*:container:_otter_container_names' \
        '(--all -a)'{--all,-a}'[Start all otter containers]' \
        '(--root -r)'{--root,-r}'[Start rootful container]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_stop() {
    _arguments \
        '*:container:_otter_container_names' \
        '(--all -a)'{--all,-a}'[Stop all otters]' \
        '(--root -r)'{--root,-r}'[Stop rootful containers]' \
        '(--force -f)'{--force,-f}'[Force stop containers]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_unlock() {
    _arguments \
        '*:container:_otter_container_names' \
        '(--all -a)'{--all,-a}'[Unlock all otter containers]' \
        '(--root -r)'{--root,-r}'[Unlock a rootful container]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter_upgrade() {
    _arguments \
        '*:container:_otter_container_names' \
        '(--all -a)'{--all,-a}'[Perform for all otters]' \
        '(--root -r)'{--root,-r}'[Upgrade rootful containers]' \
        '(--running -R)'{--running,-R}'[Only upgrade running containers]' \
        '(--help -h)'{--help,-h}'[Show this help message]'
}

_otter "$@"
