# fish completion for otter
# Drop in ~/.config/fish/completions/otter.fish
#
# Auto-generated by tools/gencompletions/generate_completions.py from
# internal/cli/show-file/*.help -- do not edit by hand.
# Run `make completions` to regenerate.

complete -c otter -f

function __otter_containers
    otter list --json 2>/dev/null | string match -r '"name": *"[^"]*"' | string replace -r '.*"name": *"([^"]*)".*' '$1'
end

function __otter_registry_images
    otter registry 2>/dev/null | tail -n +2 | awk '{print $1}'
end

function __otter_no_subcommand
    not __fish_seen_subcommand_from \
        assemble dmf \
        create mk \
        enter sh \
        generate-entry pin \
        inspect info \
        journal logs \
        list ls \
        lock lk \
        pause zz \
        registry reg \
        remove rm \
        restart rbt \
        start up \
        stop dn \
        unlock ulk \
        upgrade syu
end

function __otter_using_subcommand
    __fish_seen_subcommand_from $argv
end

# ── Global flags ──────────────────────────────────────────────────────────────
complete -c otter -n __otter_no_subcommand -l help -s h -d 'Show this help message'
complete -c otter -n __otter_no_subcommand -l version -s v -d 'Print version information'

# ── Top-level subcommands ──────────────────────────────────────────────────────
complete -c otter -n __otter_no_subcommand -a assemble -d 'Manage otter containers using manifest files (alias: dmf)'
complete -c otter -n __otter_no_subcommand -a create -d 'Create native distro like container environments using otter (alias: mk)'
complete -c otter -n __otter_no_subcommand -a enter -d 'Enter into a otter managed container environment (alias: sh)'
complete -c otter -n __otter_no_subcommand -a generate-entry -d 'Generate desktop entry for containers (alias: pin)'
complete -c otter -n __otter_no_subcommand -a inspect -d 'Show info of an otter managed container (alias: info)'
complete -c otter -n __otter_no_subcommand -a journal -d 'Show logs of an otter managed container (alias: logs)'
complete -c otter -n __otter_no_subcommand -a list -d 'List all otter managed containers (alias: ls)'
complete -c otter -n __otter_no_subcommand -a lock -d 'Lock a container to prevent removal or upgrades (alias: lk)'
complete -c otter -n __otter_no_subcommand -a pause -d 'Pause an otter managed running container (alias: zz)'
complete -c otter -n __otter_no_subcommand -a registry -d 'Browse and manage otter images from the registry (alias: reg)'
complete -c otter -n __otter_no_subcommand -a remove -d 'Remove otter managed container environments (alias: rm)'
complete -c otter -n __otter_no_subcommand -a restart -d 'Restart an otter managed container environment (alias: rbt)'
complete -c otter -n __otter_no_subcommand -a start -d 'Start an otter managed container environment (alias: up)'
complete -c otter -n __otter_no_subcommand -a stop -d 'Stop an otter managed running container environment (alias: dn)'
complete -c otter -n __otter_no_subcommand -a unlock -d 'Unlock a container to allow removal and upgrades (alias: ulk)'
complete -c otter -n __otter_no_subcommand -a upgrade -d 'Upgrade packages inside otter managed containers (alias: syu)'

# ── assemble ──────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand assemble dmf; and not __fish_seen_subcommand_from create mk remove rm' -l file -s f -d 'Path or URL to the manifest/ini file'
complete -c otter -n '__otter_using_subcommand assemble dmf; and not __fish_seen_subcommand_from create mk remove rm' -l replace -s R -d 'Replace containers with matching names'
complete -c otter -n '__otter_using_subcommand assemble dmf; and not __fish_seen_subcommand_from create mk remove rm' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand assemble dmf; and not __fish_seen_subcommand_from create mk remove rm' -a create -d 'Create or update otters defined in a manifest file (alias: mk)'
complete -c otter -n '__otter_using_subcommand assemble dmf; and not __fish_seen_subcommand_from create mk remove rm' -a remove -d 'Remove otters defined in a manifest file (alias: rm)'

# ── assemble create ───────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand assemble dmf; and __otter_using_subcommand create mk' -l file -s f -d 'Path to the manifest file (required)'
complete -c otter -n '__otter_using_subcommand assemble dmf; and __otter_using_subcommand create mk' -l replace -s R -d 'Delete and recreate boxes that already exist'
complete -c otter -n '__otter_using_subcommand assemble dmf; and __otter_using_subcommand create mk' -l help -s h -d 'Show this help message'

# ── assemble remove ───────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand assemble dmf; and __otter_using_subcommand remove rm' -l file -s f -d 'Path to the manifest file (required)'
complete -c otter -n '__otter_using_subcommand assemble dmf; and __otter_using_subcommand remove rm' -l help -s h -d 'Show this help message'

# ── create ────────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand create mk' -l home -s H -d 'Custom HOME directory for the container'
complete -c otter -n '__otter_using_subcommand create mk' -l init -s I -d 'Use init system (e.g. systemd) inside the container'
complete -c otter -n '__otter_using_subcommand create mk' -l root -s r -d 'Launch container manager with root privileges'
complete -c otter -n '__otter_using_subcommand create mk' -l clone -s C -d 'Name of container to use as base for new container'
complete -c otter -n '__otter_using_subcommand create mk' -l image -s i -d 'Image to use for the container'
complete -c otter -n '__otter_using_subcommand create mk' -l shell -s s -d 'Shell to use inside the container'
complete -c otter -n '__otter_using_subcommand create mk' -l memory -s m -d 'Memory limit for the container (e.g. 512m, 2g)'
complete -c otter -n '__otter_using_subcommand create mk' -l nvidia -s N -d 'Integrate host\'s Nvidia drivers into container'
complete -c otter -n '__otter_using_subcommand create mk' -l volume -s v -d 'Additional volumes to add to the container'
complete -c otter -n '__otter_using_subcommand create mk' -l hostname -s n -d 'Hostname for the container'
complete -c otter -n '__otter_using_subcommand create mk' -l no-entry -s E -d 'Do not generate a container entry on host system'
complete -c otter -n '__otter_using_subcommand create mk' -l platform -s P -d 'Specify the target platform, e.g. linux/arm64'
complete -c otter -n '__otter_using_subcommand create mk' -l init-hooks -s ih -d 'Commands to run at end of container initialization'
complete -c otter -n '__otter_using_subcommand create mk' -l cpu-threads -s t -d 'Number of CPU threads the container can use'
complete -c otter -n '__otter_using_subcommand create mk' -l unshare-ipc -s ui -d 'Do not share IPC namespace with host'
complete -c otter -n '__otter_using_subcommand create mk' -l unshare-all -s ua -d 'Activate all unshare flags'
complete -c otter -n '__otter_using_subcommand create mk' -l always-pull -s p -d 'Pull image even if it exists locally'
complete -c otter -n '__otter_using_subcommand create mk' -l unshare-netns -s un -d 'Do not share net namespace with host'
complete -c otter -n '__otter_using_subcommand create mk' -l pre-init-hooks -s ph -d 'Commands to run at start of container initialization'
complete -c otter -n '__otter_using_subcommand create mk' -l unshare-groups -s ug -d 'Do not forward user\'s additional groups into container'
complete -c otter -n '__otter_using_subcommand create mk' -l unshare-devsys -s ud -d 'Do not share host devices and sysfs dirs'
complete -c otter -n '__otter_using_subcommand create mk' -l unshare-process -s up -d 'Do not share process namespace with host'
complete -c otter -n '__otter_using_subcommand create mk' -l no-userns-limit -s ul -d 'Skip the size-capped userns range for podman'
complete -c otter -n '__otter_using_subcommand create mk' -l additional-flags -s a -d 'Additional flags to pass to the container manager'
complete -c otter -n '__otter_using_subcommand create mk' -l additional-packages -s ap -d 'Additional packages to install during container setup'
complete -c otter -n '__otter_using_subcommand create mk' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand create mk' -l disable-root-password-i-fully-understand-the-risks-and-accept-the-responsibilities -d ''

# ── enter ─────────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand enter sh' -l root -s r -d 'Launch container manager with root privileges'
complete -c otter -n '__otter_using_subcommand enter sh' -l no-tty -s T -d 'Do not instantiate a tty'
complete -c otter -n '__otter_using_subcommand enter sh' -l add-env -s e -d 'Comma-separated list of host env vars to copy'
complete -c otter -n '__otter_using_subcommand enter sh' -l empty-env -s E -d 'Don\'t auto copy host environment variables'
complete -c otter -n '__otter_using_subcommand enter sh' -l clean-path -d 'Reset PATH inside container to FHS standard'
complete -c otter -n '__otter_using_subcommand enter sh' -l no-workdir -s nw -d 'Always start from container\'s home directory'
complete -c otter -n '__otter_using_subcommand enter sh' -l auto-start -s S -d 'Start container if stopped, then enter'
complete -c otter -n '__otter_using_subcommand enter sh' -l additional-flags -s a -d 'Additional flags to pass to container manager'
complete -c otter -n '__otter_using_subcommand enter sh' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand enter sh' -a '(__otter_containers)'

# ── generate-entry ────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand generate-entry pin' -l all -s a -d 'Perform for all otters'
complete -c otter -n '__otter_using_subcommand generate-entry pin' -l root -s r -d 'Perform on rootful otters'
complete -c otter -n '__otter_using_subcommand generate-entry pin' -l icon -s i -d 'Specify a custom icon path'
complete -c otter -n '__otter_using_subcommand generate-entry pin' -l delete -s d -d 'Delete the entry'
complete -c otter -n '__otter_using_subcommand generate-entry pin' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand generate-entry pin' -a '(__otter_containers)'

# ── inspect ───────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand inspect info' -l root -s r -d 'Inspect a rootful container'
complete -c otter -n '__otter_using_subcommand inspect info' -l json -s j -d 'Show inspect as json struct'
complete -c otter -n '__otter_using_subcommand inspect info' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand inspect info' -a '(__otter_containers)'

# ── journal ───────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand journal logs' -l tail -s n -d 'Show last N lines'
complete -c otter -n '__otter_using_subcommand journal logs' -l since -s s -d 'Show logs since duration'
complete -c otter -n '__otter_using_subcommand journal logs' -l until -s u -d 'Show logs until duration'
complete -c otter -n '__otter_using_subcommand journal logs' -l follow -s f -d 'Stream logs live'
complete -c otter -n '__otter_using_subcommand journal logs' -l timestamps -s t -d 'Show timestamps on each line'
complete -c otter -n '__otter_using_subcommand journal logs' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand journal logs' -a '(__otter_containers)'

# ── list ──────────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand list ls' -l root -s r -d 'List rootful containers'
complete -c otter -n '__otter_using_subcommand list ls' -l json -s j -d 'Show list as json struct'
complete -c otter -n '__otter_using_subcommand list ls' -l help -s h -d 'Show this help message'

# ── lock ──────────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand lock lk' -l all -s a -d 'Lock all otter containers'
complete -c otter -n '__otter_using_subcommand lock lk' -l root -s r -d 'Lock a rootful container'
complete -c otter -n '__otter_using_subcommand lock lk' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand lock lk' -a '(__otter_containers)'

# ── pause ─────────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand pause zz' -l all -s a -d 'Pause all running otters'
complete -c otter -n '__otter_using_subcommand pause zz' -l root -s r -d 'Pause rootful containers'
complete -c otter -n '__otter_using_subcommand pause zz' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand pause zz' -a '(__otter_containers)'

# ── registry ──────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand registry reg; and not __fish_seen_subcommand_from list ls pull pl remove rm' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand registry reg; and not __fish_seen_subcommand_from list ls pull pl remove rm' -a list -d 'List otter images available in the registry (alias: ls)'
complete -c otter -n '__otter_using_subcommand registry reg; and not __fish_seen_subcommand_from list ls pull pl remove rm' -a pull -d 'Pull otter images from the registry (alias: pl)'
complete -c otter -n '__otter_using_subcommand registry reg; and not __fish_seen_subcommand_from list ls pull pl remove rm' -a remove -d 'Remove otter images from the local registry cache (alias: rm)'

# ── registry list ─────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand registry reg; and __otter_using_subcommand list ls' -l all -s a -d 'Include disabled images in the table'
complete -c otter -n '__otter_using_subcommand registry reg; and __otter_using_subcommand list ls' -l help -s h -d 'Show this help message'

# ── registry pull ─────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand registry reg; and __otter_using_subcommand pull pl' -l all -s a -d 'Pull all enabled images not yet present'
complete -c otter -n '__otter_using_subcommand registry reg; and __otter_using_subcommand pull pl' -l force -s f -d 'Pull even if already present and current'
complete -c otter -n '__otter_using_subcommand registry reg; and __otter_using_subcommand pull pl' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand registry reg; and __otter_using_subcommand pull pl' -a '(__otter_registry_images)'

# ── registry remove ───────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand registry reg; and __otter_using_subcommand remove rm' -l all -s a -d 'Remove all locally present otter images'
complete -c otter -n '__otter_using_subcommand registry reg; and __otter_using_subcommand remove rm' -l force -s f -d 'Remove even if image is in use'
complete -c otter -n '__otter_using_subcommand registry reg; and __otter_using_subcommand remove rm' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand registry reg; and __otter_using_subcommand remove rm' -a '(__otter_registry_images)'

# ── remove ────────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand remove rm' -l all -s a -d 'Delete all otters'
complete -c otter -n '__otter_using_subcommand remove rm' -l root -s r -d 'Launch container with root privileges'
complete -c otter -n '__otter_using_subcommand remove rm' -l force -s f -d 'Force deletion of problematic containers'
complete -c otter -n '__otter_using_subcommand remove rm' -l rm-home -s H -d 'Remove container\'s custom home directory'
complete -c otter -n '__otter_using_subcommand remove rm' -l bypass-lock -s B -d 'Remove container even if it is locked'
complete -c otter -n '__otter_using_subcommand remove rm' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand remove rm' -a '(__otter_containers)'

# ── restart ───────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand restart rbt' -l all -s a -d 'Restart all otter containers'
complete -c otter -n '__otter_using_subcommand restart rbt' -l root -s r -d 'Restart rootful containers'
complete -c otter -n '__otter_using_subcommand restart rbt' -l force -s f -d 'Force restart containers'
complete -c otter -n '__otter_using_subcommand restart rbt' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand restart rbt' -a '(__otter_containers)'

# ── start ─────────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand start up' -l all -s a -d 'Start all otter containers'
complete -c otter -n '__otter_using_subcommand start up' -l root -s r -d 'Start rootful container'
complete -c otter -n '__otter_using_subcommand start up' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand start up' -a '(__otter_containers)'

# ── stop ──────────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand stop dn' -l all -s a -d 'Stop all otters'
complete -c otter -n '__otter_using_subcommand stop dn' -l root -s r -d 'Stop rootful containers'
complete -c otter -n '__otter_using_subcommand stop dn' -l force -s f -d 'Force stop containers'
complete -c otter -n '__otter_using_subcommand stop dn' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand stop dn' -a '(__otter_containers)'

# ── unlock ────────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand unlock ulk' -l all -s a -d 'Unlock all otter containers'
complete -c otter -n '__otter_using_subcommand unlock ulk' -l root -s r -d 'Unlock a rootful container'
complete -c otter -n '__otter_using_subcommand unlock ulk' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand unlock ulk' -a '(__otter_containers)'

# ── upgrade ───────────────────────────────────────────────────────────────
complete -c otter -n '__otter_using_subcommand upgrade syu' -l all -s a -d 'Perform for all otters'
complete -c otter -n '__otter_using_subcommand upgrade syu' -l root -s r -d 'Upgrade rootful containers'
complete -c otter -n '__otter_using_subcommand upgrade syu' -l running -s R -d 'Only upgrade running containers'
complete -c otter -n '__otter_using_subcommand upgrade syu' -l help -s h -d 'Show this help message'
complete -c otter -n '__otter_using_subcommand upgrade syu' -a '(__otter_containers)'
