#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the otter project:
#    https://github.com/ferret-project/otter
# Copyright (C) 2026 otter contributors
#
# This file is based on distrobox:
#    https://github.com/89luca89/distrobox
# Copyright (C) 2021 distrobox contributors
#
# otter is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# otter is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with otter; if not, see <http://www.gnu.org/licenses/>.

# POSIX
# Expected env variables:
#	HOME
#	USER
#	SHELL

# Network check: verify connectivity before doing anything else.
# Runs before the borked trap so a failed check does not mark the container as borked.
# shellcheck disable=SC1091
. /usr/lib/otter/scripts/initialization-scripts/helpers/network_check.sh
network_check

# Early exit trap , errors on first faliure & creates a broked state file
# useful to distinguish a semi-broken container from a working one
trap '[ "$?" -ne 0 ] && printf "Error: An error occurred\n" && touch /usr/lib/otter/container.borked' EXIT

# Redirect stderr to stdout as podman by default logs stderr as priority 3 journald errors.
# Github issue: https://github.com/containers/podman/issues/20728
exec 2>&1

# We'll also bind mount READ-WRITE useful mountpoints to pass external drives and libvirt from
# the host to the container
# shellcheck disable=SC2034 # consumed by helpers/setup_host_mounts.sh
HOST_MOUNTS="
	/etc/host.conf
	/etc/machine-id
	/media
	/mnt
	/run/libvirt
	/run/media
	/run/netconfig/
	/run/systemd/journal
	/run/systemd/resolve/
	/run/systemd/seats
	/run/systemd/sessions
	/run/systemd/users
	/run/udev
	/var/lib/libvirt
	/var/mnt"

# We'll also bind mount in READ-ONLY useful directories from the host
# shellcheck disable=SC2034 # consumed by helpers/setup_host_mounts.sh
HOST_MOUNTS_RO="
	/etc/localtime
	/var/lib/systemd/coredump
	/var/log/journal"

HOST_MOUNTS_RO_INIT="
	/etc/localtime
	/run/systemd/journal
	/run/systemd/resolve
	/run/systemd/seats
	/run/systemd/sessions
	/run/systemd/users
	/var/lib/systemd/coredump
	/var/log/journal"

# Defaults
# shellcheck disable=SC2034 # consumed by setup_<pkgmgr>.sh helpers
container_additional_packages=""
init=0
init_hook=""
nvidia=0
pre_init_hook=""
rootful=0
upgrade=0
verbose=0
# shellcheck disable=SC2034 # consumed by helpers/parse_args.sh
version="0.0.7"

# shellcheck disable=SC1091
. /usr/lib/otter/scripts/initialization-scripts/helpers/parse_args.sh
parse_args "$@"

# Check if the container is borked or not, Fail if otter-init previously
# failed, If so then fail with a error asking user to recreate
if [ -f /usr/lib/otter/container.borked ]; then
	printf "Error: container is borked, please recreate it\n"
	exit 1
fi

# Skip/Unset first run only flags/steps
# this prevents container from breaking on reboot
# mostly useful for otter assemble as user can define
# hooks & packages which might not be needed or break
# the container or error out on a rerun.
if [ -f /usr/lib/otter/container.bootstrapped ]; then
	# shellcheck disable=SC2034 # consumed by setup_<pkgmgr>.sh helpers
	container_additional_packages=""
	pre_init_hook=""
	init_hook=""
fi

# ensure the directory is present for otter to not break
# All otter images include this directory by default
# But its kept as a fallback for non-official otter images
mkdir -p /usr/lib/otter

# Warn if this container was not built from an official otter image.
# Only warn once per container lifetime, tracked via container.user-warned.
if [ ! -f /usr/lib/otter/container.official ] && [ ! -f /usr/lib/otter/container.user-warned ]; then
	printf "Warning: this container was not built from an official otter image, your experience may vary\n"
	touch /usr/lib/otter/container.user-warned
fi

# Check we're running inside a container and not on the host
if [ ! -f /run/.containerenv ] && [ ! -f /.dockerenv ] && [ -z "${container:-}" ]; then
	printf >&2 "You must run %s inside a container!\n" " $(basename "$0")"
	printf >&2 "otter-init should only be used as an entrypoint for a otter!\n\n"
	printf >&2 "This is not intended to be used manually, but instead used by otter-enter\n"
	printf >&2 "to set up the container's entrypoint.\n"
	exit 126
fi

# Ensure the foundamental variables are set and not empty, we will not proceed if
# they are not all set.
if [ "${upgrade}" -eq 0 ]; then
	[ -z "${container_user_gid}" ] && printf "Error: Invalid arguments, missing user gid\n" && exit 2
	[ -z "${container_user_home}" ] && printf "Error: Invalid argument, missing user home\n" && exit 2
	[ -z "${container_user_name}" ] && printf "Error: Invalid arguments, missing username\n" && exit 2
	[ -z "${container_user_uid}" ] && printf "Error: Invalid arguments, missing user uid\n" && exit 2
fi

# Remove any container.ready file to prevent enter before container is ready to use
# this helps avoid enter before container is in a fully usable state or is being
# upgraded by using 'otter upgrade'
rm -f /usr/lib/otter/container.ready
if [ "${upgrade}" -ne 0 ]; then
	trap 'if [ $? -eq 0 ]; then touch /usr/lib/otter/container.ready; fi' EXIT
fi
# Add container type markers
if [ "${rootful}" -eq 1 ]; then
	touch /usr/lib/otter/container.rootful
	rm -f /usr/lib/otter/container.rootless
else
	touch /usr/lib/otter/container.rootless
	rm -f /usr/lib/otter/container.rootful
fi

set -o errexit
set -o nounset
# set verbosity
if [ "${verbose}" -ne 0 ]; then
	set -o xtrace
fi

# rootful is set explicitly via --rootful flag passed by otter-create at container creation time.

# Get host $LANG
if [ -f "/run/host/etc/locale.conf" ]; then
	HOST_LOCALE=$(grep -e '^LANG=' /run/host/etc/locale.conf | sed 's/LANG=//' | sed 's/"//g' | sed "s/'//g")
	# shellcheck disable=SC2034 # consumed downstream (locale setup)
	HOST_LOCALE_ENCODING=$(echo "${HOST_LOCALE}" | sed -n 's/^[^.]*\.\(.*\)$/\1/p')
	# shellcheck disable=SC2034 # consumed downstream (locale setup)
	HOST_LOCALE_LANG=$(echo "${HOST_LOCALE}" | sed -n 's/^\([^.]*\)\..*$/\1/p')
elif [ -f "/run/host/etc/default/locale" ]; then
	HOST_LOCALE=$(grep -e '^LANG=' /run/host/etc/default/locale | sed 's/LANG=//' | sed 's/"//g')
	HOST_LOCALE_ENCODING=$(echo "${HOST_LOCALE}" | sed -n 's/^[^.]*\.\(.*\)$/\1/p')
	HOST_LOCALE_LANG=$(echo "${HOST_LOCALE}" | sed -n 's/^\([^.]*\)\..*$/\1/p')
fi
# Add fallback values in case host's locale is not set correctly
if [ -z "${HOST_LOCALE:-}" ] || [ "${HOST_LOCALE:-}" = "C.UTF-8" ]; then
	HOST_LOCALE="en_US.UTF-8"
	# shellcheck disable=SC2034 # consumed downstream (locale setup)
	HOST_LOCALE_ENCODING="UTF-8"
	# shellcheck disable=SC2034 # consumed downstream (locale setup)
	HOST_LOCALE_LANG="en_US"
fi

# get_locked_mount_flags will print mount flags considered "locked".
# Arguments:
# 	src: path to the file/directory
# Expected env variables:
#	None
# Expected global variables:
#	None
# Outputs:
# 	Comma-separated list of locked mount flags
get_locked_mount_flags()
{
	src="$1"
	prev=""
	locked_flags=""

	# If findmnt does not exist, exit
	if ! command -v findmnt 2> /dev/null > /dev/null; then
		return 0
	fi

	# If we can't read the file/directory, exit
	if ! ls "${src}" 2> /dev/null > /dev/null; then
		return 0
	fi

	# Get mount flags of given file/directory, using nearest mountpoint.
	# Earlier versions of findmnt did not check parents until it found a mountpoint,
	# so we use a workaround with dirname.
	while true; do
		flags="$(findmnt --noheadings --output OPTIONS --target "${src}" || :)"
		# shellcheck disable=SC2181
		if [ -n "${flags}" ]; then
			break
		fi
		prev="${src}"
		src="$(dirname "${src}")"
		[ "${src}" = "${prev}" ] && return 1
	done

	for flag in nodev noexec nosuid; do
		if printf "%s" "${flags}" | grep -q "${flag}"; then
			# Locked flag found, append to list while avoiding leading/trailing commas
			locked_flags="${locked_flags:+${locked_flags},}${flag}"
		fi
	done

	printf "%s" "${locked_flags}"
}

# init_readlink is a simplistic implementation for
# readlink -fm
# we use this as readlink -fm does not work on
# busybox systems, and we need the path even for broken links.
# Arguments:
#	source file
# Expected env variables:
#	None
# Expected global variables:
#	None
# Outputs:
#	original path the link is pointing
init_readlink()
{
	# shellcheck disable=SC2010
	ls -l "${1}" | grep -Eo '\->.*' | cut -d' ' -f2- | sed 's|\.\./|/|g'
}

# mount_bind will perform a bind mount for inputs or error
# Arguments:
#   source_dir: string what to mount
#	target_dir: string where to mount
#	mount_flags: list of mount flags -> optional
# Expected env variables:
#	None
# Expected global variables:
#	None
# Outputs:
#   No output if all ok
#	Error if not
mount_bind()
{
	source_dir="$1"
	target_dir="$2"
	mount_flags=""
	if [ "$#" -gt 2 ]; then
		mount_flags="$3"
	fi

	# Adjust source_dir in order to point to /run/host if it's a symlink
	if [ -L "${source_dir}" ]; then
		source_dir="$(init_readlink "${source_dir}")"
		if ! printf "%s" "${source_dir}" | grep -q "/run/host"; then
			source_dir="/run/host${source_dir}"
		fi
	fi

	# if source dir doesn't exist, just exit
	if [ ! -d "${source_dir}" ] && [ ! -f "${source_dir}" ]; then
		return 0
	fi

	# if target_dir exists, check if it is a mountpoint and umount it.
	if [ -e "${target_dir}" ] && findmnt "${target_dir}" > /dev/null; then
		umount "${target_dir}"
	fi

	# if target_dir exists, and is a symlink, remove it
	if [ -L "${target_dir}" ]; then
		rm -f "${target_dir}"
	fi

	# if the source_dir exists, then create the target_dir
	if [ -d "${source_dir}" ]; then
		if ! mkdir -p "${target_dir}"; then
			printf "Warning: cannot create mount target directory: %s\n" "${target_dir}"
			return 1
		fi
	# if instead it's a file, create it with touch
	elif [ -f "${source_dir}" ]; then
		if [ ! -d "$(dirname "${target_dir}")" ]; then
			mkdir -p "$(dirname "${target_dir}")"
		fi
		# if we encounter a broken link, and we touch it
		# then remove the broken link, the next touch
		# will cover it.
		if ! touch "${target_dir}"; then
			printf "Warning: cannot create mount target file: %s\n" "${target_dir}"
			return 1
		fi
	fi

	# Add mountflags if needed, if no are specified, use rslave as default.
	# bind mount source_dir to target_dir, return error if not successful
	if [ "${mount_flags}" = "" ]; then
		if ! mount --rbind "${source_dir}" "${target_dir}"; then
			printf "Warning: failed to bind mount %s to %s\n" "${source_dir}" "${target_dir}"
			return 1
		fi
		if ! mount --make-rslave "${target_dir}"; then
			printf "Warning: failed to make rslave to %s\n" "${target_dir}"
			return 1
		fi
	elif ! mount --rbind -o "${mount_flags}" "${source_dir}" "${target_dir}"; then
		printf "Warning: failed to bind mount %s to %s using option %s\n" "${source_dir}" "${target_dir}" "${mount_flags}"
		return 1
	fi

	return 0
}

if [ -n "${pre_init_hook}" ]; then
	printf "otter: Executing pre-init hooks...\n"
	# execute pre-init hooks if specified
	# shellcheck disable=SC2086
	eval ${pre_init_hook}
fi

###############################################################################
printf "otter: Installing basic packages...\n"
# Extract shell name from the $SHELL environment variable
# If not present as package in the container, we want to install it.
shell_pkg="$(basename "${SHELL:-"bash"}")"
# Ash shell is an exception, it is not a standalone package, but part of busybox.
# for this reason, use this quirk to adjust the package name to standard bash.
if [ "${shell_pkg}" = "ash" ]; then
	shell_pkg="bash"
fi

# get_distro_id will read the ID field from /etc/os-release, falling back to
# /usr/lib/os-release, and print it. Exits with an error if neither file
# exists.
# Arguments:
#   None
# Expected global variables:
#   None
# Expected env variables:
#   None
# Outputs:
#   The distro ID (e.g. alpine, wolfi, chimera, ubuntu, debian, devuan)
get_distro_id()
{
	if [ -e /etc/os-release ]; then
		# shellcheck disable=SC1091
		. /etc/os-release
	elif [ -e /usr/lib/os-release ]; then
		# shellcheck disable=SC1091
		. /usr/lib/os-release
	else
		printf "Error: could not find /etc/os-release or /usr/lib/os-release.\n" >&2
		printf "Error: could not determine the distro of this container.\n" >&2
		exit 127
	fi
	printf "%s" "${ID}"
}

# setup_pkg_manager_hooks will create umount/remount hooks script for a package
# manager. Mainly used by apt and pacman.
# Arguments:
#   None
# Expected global variables:
#   init: if this is an initful container
#   HOST_MOUNTS_RO_INIT: list of mountpoints of an initful system, to avoid
# Expected env variables:
#   None
# Outputs:
#   None
setup_pkg_manager_hooks()
{
	if {
		[ -d "/etc/dpkg/dpkg.cfg.d/" ] || [ -d "/usr/share/libalpm/scripts" ]
	} && [ "${init}" -eq 0 ]; then
		cat << EOF > /etc/otter-pre-hook.sh
#!/bin/sh
mounts="${HOST_MOUNTS_RO_INIT}"
for mount in \$mounts; do
	if findmnt \$mount >/dev/null; then
		umount -l \$mount
	fi
done
EOF
		cat << EOF > /etc/otter-post-hook.sh
#!/bin/sh
mounts="${HOST_MOUNTS_RO_INIT}"
for mount in \$mounts; do
	if [ -e /run/host/\$mount ] || [ -e /run/host/\$(readlink -fm /run/host/\$mount) ]; then
		if [ ! -d /run/host/\$mount ]; then
			rm -f \$mount && touch \$mount
		fi
		if ! mount --rbind \$(readlink -fm /run/host/\$mount) \$mount; then
			mount --rbind /run/host/\$(readlink -fm /run/host/\$mount) \$mount
		fi
	fi
done
EOF
		chmod +x /etc/otter-pre-hook.sh /etc/otter-post-hook.sh
	fi
}

# setup_tmpfiles_exceptions masks the systemd-tmpfiles configs that chown paths
# bind mounted from the host.
# Arguments:
#   None
# Expected global variables:
#   None
# Expected env variables:
#   None
# Outputs:
#   None
setup_tmpfiles_exceptions()
{
	mkdir -p /etc/tmpfiles.d
	for tmpfiles_conf in \
		tmp.conf x11.conf systemd-tmp.conf openssh-client.conf \
		tpm-udev.conf tpm2-tss-fapi.conf; do
		ln -sf /dev/null "/etc/tmpfiles.d/${tmpfiles_conf}"
	done
}

# Check if all commands are installed.
# Arguments:
#   None
# Expected global variables:
#   shell_pkg: shell package of the container shell
# Expected env variables:
#   None
# Outputs:
#   None
check_missing_packages()
{
	dependencies="
		bc
		bzip2
		chpasswd
		curl
		diff
		find
		findmnt
		gpg
		hostname
		less
		lsof
		man
		mount
		passwd
		pigz
		pinentry
		ping
		ps
		rsync
		script
		ssh
		sudo
		time
		tree
		umount
		unzip
		useradd
		wc
		wget
		xauth
		zip
		${shell_pkg}
	"
	for dep in ${dependencies}; do
		! command -v "${dep}" && return 1
	done
	return 0
}

# Ensure we have the least minimal path of standard Linux File System set
PATH="${PATH}:/bin:/sbin:/usr/bin:/usr/sbin"

# Mask systemd-tmpfiles rules over host-shared paths before any package manager
# runs its maintainer scripts.
setup_tmpfiles_exceptions

# Setup pkg manager exceptions and excludes
if command -v apt-get; then
	# shellcheck disable=SC1091
	. /usr/lib/otter/scripts/initialization-scripts/setup_apt.sh
	setup_deb_exceptions
elif command -v pacman; then
	# shellcheck disable=SC1091
	. /usr/lib/otter/scripts/initialization-scripts/setup_pacman.sh
	setup_pacman_exceptions
elif command -v xbps-install; then
	# shellcheck disable=SC1091
	. /usr/lib/otter/scripts/initialization-scripts/setup_xbps.sh
	setup_xbps_exceptions
elif command -v zypper; then
	# shellcheck disable=SC1091
	. /usr/lib/otter/scripts/initialization-scripts/setup_rpm_exceptions.sh
	setup_rpm_exceptions
elif command -v dnf; then
	# shellcheck disable=SC1091
	. /usr/lib/otter/scripts/initialization-scripts/setup_rpm_exceptions.sh
	setup_rpm_exceptions
fi

# Check if dependencies are met for the script to run.
if [ "${upgrade}" -ne 0 ] || [ ! -e /.containersetupdone ]; then

	# Detect the available package manager
	# install minimal dependencies needed to bootstrap the container:
	#	the same shell that's on the host + ${dependencies}
	if command -v apk; then
		# shellcheck disable=SC1091
		. /usr/lib/otter/scripts/initialization-scripts/setup_apk.sh
		setup_apk
	elif command -v apt-get; then
		# shellcheck disable=SC1091
		. /usr/lib/otter/scripts/initialization-scripts/setup_apt.sh
		setup_apt
	elif command -v emerge; then
		# shellcheck disable=SC1091
		. /usr/lib/otter/scripts/initialization-scripts/setup_emerge.sh
		setup_emerge
	elif command -v pacman; then
		# shellcheck disable=SC1091
		. /usr/lib/otter/scripts/initialization-scripts/setup_pacman.sh
		setup_pacman
	elif command -v xbps-install; then
		# shellcheck disable=SC1091
		. /usr/lib/otter/scripts/initialization-scripts/setup_xbps.sh
		setup_xbps
	elif command -v zypper; then
		# shellcheck disable=SC1091
		. /usr/lib/otter/scripts/initialization-scripts/setup_zypper.sh
		setup_zypper
	elif command -v dnf; then
		# shellcheck disable=SC1091
		. /usr/lib/otter/scripts/initialization-scripts/setup_dnf.sh
		setup_dnf dnf
	elif command -v slackpkg; then
		# shellcheck disable=SC1091
		. /usr/lib/otter/scripts/initialization-scripts/setup_slackpkg.sh
		setup_slackpkg
	elif command -v nix; then
		# shellcheck disable=SC1091
		. /usr/lib/otter/scripts/initialization-scripts/setup_nix.sh
		setup_nix
	else
		printf "Error: could not find a supported package manager.\n"
		printf "Error: could not set up base dependencies.\n"
		# Exit as command not found
		exit 127
	fi
	if [ ! -e /.containersetupdone ]; then
		if ! check_missing_packages; then
			printf "Warning: some dependencies are missing.\n"
		fi
		touch /.containersetupdone
	fi
fi

# Set SHELL to the install path inside the container
SHELL="$(command -v "${shell_pkg}")"

# Fix broken prompt for zsh shell (debian, ubuntu... need it)
if [ "${shell_pkg}" = "zsh" ]; then
	mkdir -p /etc/zsh
	printf 'emulate sh -c '\''source /etc/profile'\''\n' > /etc/zsh/zprofile
	printf 'emulate sh -c '\''source /etc/profile'\''\n' > /etc/zshenv
	printf '[ -f /etc/profile.d/otter_profile.sh ] && source /etc/profile.d/otter_profile.sh\n' >> /etc/zsh/zprofile
fi

# Attempt to download host-spawn during init, we don't care if it fails, so let's
# continue in that case
/usr/lib/otter/scripts/otter-host-exec -Y test 2> /dev/null > /dev/null || :

# If xdg-open is not present and we don't have an init system, do a link of it.
# This is handy to handle opening of links, files and apps from inside the container
# into the host.
if [ "${init}" -eq 0 ] && ! command -v xdg-open; then
	mkdir -p /usr/local/bin/
	ln -sf /usr/lib/otter/scripts/otter-host-exec /usr/local/bin/xdg-open
fi

# If flatpak is not present, do a link of it. This is handy to handle opening of
# links, files and apps from inside the container into the host.
# Note: we're using /usr/bin instead of /usr/local/bin because xdg-open will read
# the desktopfile, which will contain an absolute path of /usr/bin/flatpak
if ! command -v flatpak; then
	ln -sf /usr/lib/otter/scripts/otter-host-exec /usr/bin/flatpak
fi

###############################################################################

# Ensure compatibility with older versions of su, this will allow to specify
# the --pty flag
#
# This won't work well on very old distros with su version from util-linux
# before version 2.34 or other su implementations but will give an usable
# shell nonetheless
if [ ! -e /usr/local/bin/su ] && {
	! su --version | grep -q util-linux ||
		su --version | awk '{printf  "%s\n%s", $4, 2.34}' | sort --check=quiet --version-sort
}; then
	cp /usr/lib/otter/scripts/initialization-scripts/configs/su-pty-wrapper.sh /usr/local/bin/su
	chmod +x /usr/local/bin/su
fi

###############################################################################
printf "otter: Setting up devpts mounts...\n"

# First we need to ensure we have a tty group to assign /dev/pts to
if ! grep -q tty /etc/group; then
	printf "%s" 'tty:x:5:' >> /etc/group
fi

# Instantiate a new /dev/pts mount, this will ensure pseudoterminals are container-scoped
# and make easier in case of initful containers to have a separate /dev/console
#
# Podman supports a mount option to do this at creation time, but we're doing it
# here to support also other container rmanagers which does not support that flag
mount -t devpts devpts -o noexec,nosuid,newinstance,ptmxmode=0666,mode=0620,gid=tty /dev/pts/
mount --bind /dev/pts/ptmx /dev/ptmx

# Change mount propagation to shared to make the environment more similar to a
# modern Linux system, e.g. with Systemd as PID 1.
mount --make-rshared /
###############################################################################

# shellcheck disable=SC1091
. /usr/lib/otter/scripts/initialization-scripts/helpers/setup_host_mounts.sh
setup_host_mounts

###############################################################################
if [ "${nvidia}" -eq 1 ]; then
	# shellcheck disable=SC1091
	. /usr/lib/otter/scripts/initialization-scripts/setup_nvidia_gpu.sh
	setup_nvidia_gpu
fi

###############################################################################
printf "otter: Integrating host's themes, icons, fonts...\n"
# Themes and icons integration works using a bind mount inside the container
# of the host's themes and icons directory. This ensures that the host's home will
# not be littered with files and directories and broken symlinks.
if ! mount_bind "/run/host/usr/share/themes" "/usr/local/share/themes"; then
	printf "Warning: Cannot bind mount /run/host/usr/share/themes to /usr/local/share/themes\n"
	printf "Warning: Themes integration with the host is disabled.\n"
fi
if ! mount_bind "/run/host/usr/share/icons" "/usr/local/share/icons"; then
	printf "Warning: Cannot bind mount /run/host/usr/share/icons to /usr/local/share/icons\n"
	printf "Warning: Icons integration with the host is disabled.\n"
fi
if ! mount_bind "/run/host/usr/share/fonts" "/usr/local/share/fonts"; then
	printf "Warning: Cannot bind mount /run/host/usr/share/fonts to /usr/local/share/fonts\n"
	printf "Warning: Fonts integration with the host is disabled.\n"
fi
###############################################################################

printf "otter: Setting up container profile...\n"

# This ensures compatibility with prompts and tools between toolbx and otter
touch /run/.toolboxenv

# Ensure we have some basic env variables and prompt as base if /etc/profile.d is missing
if [ ! -d /etc/profile.d ]; then
	rcfiles="
		/etc/profile
		/etc/bash.bashrc
		/etc/bashrc
		/etc/zshrc
	"
	for rcfile in ${rcfiles}; do
		if [ -e "${rcfile}" ] && ! grep -q 'otter_profile.sh' "${rcfile}"; then
			echo "[ -e /etc/profile.d/otter_profile.sh ] && . /etc/profile.d/otter_profile.sh" >> "${rcfile}"
		fi
	done
	mkdir -p /etc/profile.d
fi
cp /usr/lib/otter/scripts/initialization-scripts/configs/otter_profile.sh /etc/profile.d/otter_profile.sh

# It's also importanto to keep this working on fish shells
if [ -e "/etc/fish/config.fish" ]; then
	mkdir -p /etc/fish/conf.d
	cp /usr/lib/otter/scripts/initialization-scripts/configs/otter_config.fish /etc/fish/conf.d/otter_config.fish
	mkdir -p /etc/fish/functions
	cp /usr/lib/otter/scripts/initialization-scripts/configs/fish_prompt.fish /etc/fish/functions/fish_prompt.fish
fi
###############################################################################

###############################################################################
printf "otter: Setting up sudo...\n"
mkdir -p /etc/sudoers.d
# Ensure we're using the user's password for sudo, not root
if [ -e /etc/sudoers ]; then
	sed -i "s|^Defaults targetpw.*||g" /etc/sudoers
fi

# Do not check fqdn when doing sudo, it will not work anyways
# Also allow canonical groups to use sudo
cp /usr/lib/otter/scripts/initialization-scripts/configs/sudoers /etc/sudoers.d/sudoers
# ditto for doas
if [ -e /etc/doas.conf ]; then
	cp /usr/lib/otter/scripts/initialization-scripts/configs/doas.conf /etc/doas.conf
fi
# if no sudo but doas is present, we want to have it as an alias
# of sudo, so other part of the program will find it as expected
if command -v doas && ! command -v sudo; then
	ln -sf "$(command -v doas)" /usr/bin/sudo
fi

# PAM config for "su" command
if [ ! -e /etc/pam.d/su ]; then
	mkdir -p /etc/pam.d
	cp /usr/lib/otter/scripts/initialization-scripts/configs/pam-su /etc/pam.d/su
fi

if ! grep -q "pam_systemd.so" /etc/pam.d/su; then
	printf "%s" '-session   optional   pam_systemd.so' >> /etc/pam.d/su
fi

# If we're running this script as root in a login shell (sudoless), we don't
# have to bother setting up sudo.
#
# Also if we're in a rootful container, we will setup user's password,
# so let's skip passwordless sudo too
if [ "${container_user_uid}" -ne 0 ] && [ "${rootful}" -eq 0 ]; then
	# Ensure passwordless sudo is set up for user
	printf "\"%s\" ALL = (root) NOPASSWD:ALL\n" "${container_user_name}" >> /etc/sudoers.d/sudoers
	# ditto for doas
	if [ -e /etc/doas.conf ]; then
		printf "permit nopass %s\n" "${container_user_name}" >> /etc/doas.conf
	fi
fi
###############################################################################

# shellcheck disable=SC1091
. /usr/lib/otter/scripts/initialization-scripts/helpers/setup_user.sh
setup_user

###############################################################################
if [ -n "${OTTER_HOST_HOME-}" ] && [ -d "/etc/skel" ]; then
	printf "otter: Setting up skel...\n"

	# If we do not have profile files in the home, we should copy the
	# skeleton files, if present.
	# Ensure we copy only if the dotfile is not already present.
	skel_files="$(find /etc/skel/ -type f || :)"
	for skel_file in ${skel_files}; do
		base_file_name=$(basename "${skel_file}")
		skel_file_path=$(dirname "${skel_file}")
		file_path_for_home=${skel_file_path#/etc/skel}

		if [ -n "${file_path_for_home}" ] &&
			[ ! -d "${container_user_home}/${file_path_for_home:+"${file_path_for_home}"}" ]; then
			mkdir -p "${container_user_home}/${file_path_for_home:+"${file_path_for_home}"/}"
			chown "${container_user_uid}":"${container_user_gid}" "${container_user_home}/${file_path_for_home:+"${file_path_for_home}"/}"
		fi

		if [ ! -f "${container_user_home}/${file_path_for_home:+"${file_path_for_home}"/}${base_file_name}" ] &&
			[ ! -L "${container_user_home}/${file_path_for_home:+"${file_path_for_home}"/}${base_file_name}" ]; then
			cp "${skel_file}" "${container_user_home}/${file_path_for_home:+"${file_path_for_home}"/}${base_file_name}"
			chown "${container_user_uid}":"${container_user_gid}" "${container_user_home}/${file_path_for_home:+"${file_path_for_home}"/}${base_file_name}"
		fi

	done
fi
###############################################################################

###############################################################################
# A fresh custom home has none of the standard XDG user directories
# (Documents, Downloads, etc.) that a real host home would already have.
# Seed them here, custom-home only, matching the skel-seeding logic above.
if [ -n "${OTTER_HOST_HOME-}" ] && command -v xdg-user-dirs-update > /dev/null 2>&1; then
	printf "otter: Setting up XDG user dirs...\n"

	# A recursive chown (rather than a hardcoded English directory-name list) is
	# used here since xdg-user-dirs-update localizes directory names based on
	# the container's locale (e.g. "Dokumente" instead of "Documents").
	if HOME="${container_user_home}" xdg-user-dirs-update; then
		chown -R "${container_user_uid}":"${container_user_gid}" "${container_user_home}"
	fi
fi
###############################################################################

###############################################################################
if [ -n "${init_hook}" ]; then
	printf "otter: Executing init hooks...\n"
	# execute eventual init hooks if specified
	# shellcheck disable=SC2086
	eval ${init_hook}
fi
###############################################################################

HOST_WATCH="
	/etc/hostname
	/etc/hosts
	/etc/localtime
	/etc/resolv.conf
"
id="${CONTAINER_ID:-}"
if [ -e /run/.containerenv ]; then
	# shellcheck disable=SC1091,SC2034
	. /run/.containerenv
elif [ -e /.dockerenv ]; then
	id="$(curl -s --unix-socket /run/docker.sock http://docker/containers/"${CONTAINER_ID:-$(hostname | cut -d'.' -f1)}"/json |
		grep -Eo '"Id":"[a-zA-Z0-9]{64}",' | cut -d '"' -f4)"
fi

###############################################################################
# If init support is disabled, let's do our routine to keep the container
# up, running and in sync with host.
#
# For non-init containers, the init will stop here
if [ "${init}" -eq 0 ]; then
	touch /usr/lib/otter/container.ready
	touch /usr/lib/otter/container.bootstrapped
	printf "container_setup_done\n"
	# Keepalive loop
	# disable verbose logging for this phase.
	set +x
	while true; do
		# Let's check for changes every 15 seconds.
		# This way we can dynamically keep hosts, dns and timezone setups
		# in sync with host, without having permissions problems:
		#	- symlink will fail with "Device or Resource busy"
		#	- bindmount will need a container restart on changes
		for file_watch in ${HOST_WATCH}; do
			# do stuff, only if the file is a mountpoint, and if the mountpoint is NOT containing the
			# container id, because if it does, it is because it's part of the podman/docker setup
			# The mount point might not exist, either because it's umounted or it doesn't exist on
			# host in some cases like /etc/localtime, so ignore findmnt errors
			mount_source="$(findmnt -no SOURCE "${file_watch}")" || :
			if [ -n "${mount_source}" ] && ! echo "${mount_source}" | grep -q "${id}"; then
				file_watch_src="/run/host${file_watch}"
				# check if the target file exists
				if ls -l "${file_watch_src}" 2> /dev/null > /dev/null; then
					# if it's a symlink and take the source
					if [ -L "${file_watch_src}" ]; then
						file_watch_src="$(init_readlink "/run/host${file_watch}")"
						# if it's an absolute link, we need to append /run/host ourselves.
						if ! printf "%s" "${file_watch_src}" | grep -q "/run/host"; then
							file_watch_src="/run/host${file_watch_src}"
						fi
					fi
					if ! diff "${file_watch}" "${file_watch_src}" > /dev/null; then
						# We only do this, if the file is actually different
						umount "${file_watch}" &&
							mount_bind "${file_watch_src}" "${file_watch}"

						# Let's keep in sync host's hostname and container's hostname
						if [ "${file_watch}" = "/etc/hostname" ]; then
							hostname "$(cat /etc/hostname)"
						fi
					fi
				fi
			fi
		done
		sleep 15
	done
fi
###############################################################################

# shellcheck disable=SC1091
. /usr/lib/otter/scripts/initialization-scripts/setup_initsystem.sh
setup_initsystem
