# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the otter project:
#    https://github.com/ferret-linux/otter
# Copyright (C) 2026 otter contributors

name: .ib-merge

on:
  workflow_call:

jobs:
  load-matrix:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.filter.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Filter matrix
        id: filter
        run: |
          matrix=$(jq -c '[.[] | select(.enabled == true)]' images/images.json)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  merge:
    needs: load-matrix
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.load-matrix.outputs.matrix) }}

    steps:
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create and Push Manifest
        run: |
          ARCHES='${{ toJson(matrix.arches) }}'
          if echo "$ARCHES" | jq -e 'contains(["arm64"])' > /dev/null; then
            podman manifest create \
              ghcr.io/ferret-linux/${{ matrix.name }}:${{ matrix.tag }} \
              ghcr.io/ferret-linux/${{ matrix.name }}:${{ matrix.tag }}-amd64 \
              ghcr.io/ferret-linux/${{ matrix.name }}:${{ matrix.tag }}-arm64
          else
            podman manifest create \
              ghcr.io/ferret-linux/${{ matrix.name }}:${{ matrix.tag }} \
              ghcr.io/ferret-linux/${{ matrix.name }}:${{ matrix.tag }}-amd64
          fi
          podman manifest push \
            ghcr.io/ferret-linux/${{ matrix.name }}:${{ matrix.tag }} \
            docker://ghcr.io/ferret-linux/${{ matrix.name }}:${{ matrix.tag }}