# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the otter project:
#    https://github.com/ferret-linux/otter
# Copyright (C) 2026 otter contributors

name: .ib-merge

on:
  workflow_call:

jobs:
  merge:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-otr
            tag: stable
          - name: ubuntu-otr
            tag: lts
          - name: debian-otr
            tag: stable
          - name: debian-otr
            tag: testing
          - name: debian-otr
            tag: unstable
          - name: fedora-otr
            tag: stable
          - name: fedora-otr
            tag: rawhide
          - name: arch-otr
            tag: latest
            amd64_only: true
          - name: blackarch-otr
            tag: latest
            amd64_only: true
          - name: gentoo-otr
            tag: stage3
          - name: alma-otr
            tag: stable
          - name: rocky-otr
            tag: stable
          - name: centos-otr
            tag: stable
          - name: oracle-otr
            tag: stable
          - name: rhel-otr
            tag: stable
          - name: opensuse-otr
            tag: leap
          - name: opensuse-otr
            tag: tumbleweed
          - name: alpine-otr
            tag: latest
          - name: alpine-otr
            tag: edge
          - name: kali-otr
            tag: rolling
          - name: kali-otr
            tag: edge
          - name: void-otr
            tag: glibc
          - name: void-otr
            tag: musl

    steps:
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create and Push Manifest
        run: |
          if [ "${{ matrix.amd64_only }}" = "true" ]; then
            podman manifest create \
              ghcr.io/ferret-linux/${{ matrix.name }}:${{ matrix.tag }} \
              ghcr.io/ferret-linux/${{ matrix.name }}:${{ matrix.tag }}-amd64
          else
            podman manifest create \
              ghcr.io/ferret-linux/${{ matrix.name }}:${{ matrix.tag }} \
              ghcr.io/ferret-linux/${{ matrix.name }}:${{ matrix.tag }}-amd64 \
              ghcr.io/ferret-linux/${{ matrix.name }}:${{ matrix.tag }}-arm64
          fi
          podman manifest push \
            --compression-format zstd:chunked \
            ghcr.io/ferret-linux/${{ matrix.name }}:${{ matrix.tag }} \
            docker://ghcr.io/ferret-linux/${{ matrix.name }}:${{ matrix.tag }}