# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the otter project:
#    https://github.com/ferret-linux/otter
# Copyright (C) 2026 otter contributors

name: Image Builder (IB)

on:
  schedule:
    - cron: '13 16 * * *'
    - cron: '21 06 * * *'
  workflow_dispatch:

jobs:
  build-amd64:
    uses: ./.github/workflows/.ib-x64-imgs.yml
    permissions:
      contents: read
      packages: write

  build-arm64:
    uses: ./.github/workflows/.ib-arm-imgs.yml
    permissions:
      contents: read
      packages: write

  push:
    needs: [build-amd64, build-arm64]
    uses: ./.github/workflows/.ib-push-imgs.yml
    permissions:
      contents: read
      packages: write

  merge:
    needs: [push]
    uses: ./.github/workflows/.ib-merge-imgs.yml
    permissions:
      contents: read
      packages: write

  verify:
    needs: [merge]
    uses: ./.github/workflows/.ib-verify-imgs.yml
    permissions:
      contents: read
      packages: read

  purge:
    needs: [verify]
    if: failure()
    uses: ./.github/workflows/.ib-purge-imgs.yml
    permissions:
      contents: read
      packages: write