# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the otter project:
#    https://github.com/ferret-linux/otter
# Copyright (C) 2026 otter contributors

name: 1.Image Builder (IB)

on:
  schedule:
    - cron: '27 8 */2 * *'
  workflow_dispatch:

jobs:
  build-amd64:
    uses: ./.github/workflows/.ib-x64-imgs.yml
    permissions:
      contents: read
      packages: write

  build-arm64:
    uses: ./.github/workflows/.ib-arm-imgs.yml
    permissions:
      contents: read
      packages: write

  sbom-scan:
    needs: [build-amd64, build-arm64]
    uses: ./.github/workflows/.ib-sbom-scan.yml
    permissions:
      contents: read

  grype:
    needs: [sbom-scan]
    uses: ./.github/workflows/.ib-grype.yml
    permissions:
      contents: read

  push:
    needs: [grype]
    uses: ./.github/workflows/.ib-push-imgs.yml
    permissions:
      contents: read
      packages: write
      id-token: write

  attest:
    needs: [push]
    uses: ./.github/workflows/.ib-attest.yml
    permissions:
      contents: read
      packages: write
      id-token: write

  merge:
    needs: [attest]
    uses: ./.github/workflows/.ib-merge-imgs.yml
    permissions:
      contents: read
      packages: write
      id-token: write

  verify:
    needs: [merge]
    uses: ./.github/workflows/.ib-verify-imgs.yml
    permissions:
      contents: read
      packages: read

  update-props:
    needs: [verify]
    uses: ./.github/workflows/.ib-update-props.yml
    permissions:
      contents: write
      packages: read
    secrets: inherit

  purge:
    needs: [push, attest, merge, verify]
    if: |
      always() && (
        needs.push.result == 'failure' ||
        (needs.push.result == 'success' && (
          needs.attest.result == 'failure' ||
          needs.merge.result == 'failure' ||
          needs.verify.result == 'failure'
        ))
      )
    uses: ./.github/workflows/.ib-purge-imgs.yml
    permissions:
      contents: write
      packages: write
    secrets: inherit